version: '2.0'

services:
  app:
    image: 'br2:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bicycleracing
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - db-data:/var/lib/postgresql/data
    #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bicycleracing
